SCREEN_WIDTH = 350
SCREEN_HEIGHT = 350

STEP = 50

TURTLE_HEIGHT = 20
BRICK_WIDTH_FACTOR = 2
BRICK_WIDTH = BRICK_WIDTH_FACTOR * TURTLE_HEIGHT

NUM_TURNS = 3

NUM_BRICK_COLS = 14
NUM_BRICK_ROWS = 8
BRICK_SCORING = {
    "red": 7,
    "orange": 5,
    "green": 3,
    "yellow": 1,
}


PADDLE_WIDTH_FACTOR = 2 * BRICK_WIDTH_FACTOR
PADDLE_WIDTH = TURTLE_HEIGHT * PADDLE_WIDTH_FACTOR

DISPLAY_ALIGNMENT = "center"
SCORE_DISPLAY_FONT = ("Courier", 80, "normal")
DISPLAY_FONT = ("Courier", 25, "normal")
GAME_OVER_FONT = ("Courier", 100, "normal")
