SCREEN_WIDTH = 350
SCREEN_HEIGHT = 350

STEP = 20

TURTLE_HEIGHT = 20
BRICK_WIDTH_FACTOR = 2
BRICK_WIDTH = BRICK_WIDTH_FACTOR * TURTLE_HEIGHT

NUM_TURNS = 3

NUM_BRICK_COLS = 14
NUM_BRICK_ROWS = 8
BRICK_SCORING = {
    "red": 7,
    "orange": 5,
    "green": 3,
    "yellow": 1,
}

BRICK_WIDTH = SCREEN_WIDTH // NUM_BRICK_COLS

PADDLE_WIDTH = BRICK_WIDTH * 2
